# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Syh's Blog"
baseURL = "https://seeuswk.github.io/lanaya/"
theme = "FixIt"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
languageName = "简体中文"
disableLanguages = ["en", "zh-tw"]
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
withSiteTitle = false
disableThemeInject = true
